remote_theme: YoussefRaafatNasry/portfolYOU

title: Lohit Inguva - Data Engineer & Cloud Architect
email: lohit.inguva@gmail.com
description: >
  Portfolio of Lohit Inguva, specializing in data engineering, cloud architecture, and analytics consulting.

baseurl: ""
url: "https://lohitinguva.github.io"

author:
  name: Lohit Inguva
  image: https://lohitinguva.github.io/assets/images/profile.jpg
  email: lohit.inguva@gmail.com
  github: lohitinguva
  linkedin: lohitinguva

collections:
  projects:
    output: true
    permalink: /projects/:name
  posts:
    output: true
    permalink: /blog/:title/

nav:
  - name: Home
    link: /
  - name: Projects
    link: /projects/
  - name: Blog
    link: /blog/
  - name: About
    link: /about/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
