remote_theme: YoussefRaafatNasry/portfolYOU

title: Lohit Inguva - Data Engineer & Cloud Architect
email: lohit.inguva@gmail.com
description: Cloud and data engineering professional with 9+ years of experience delivering enterprise-scale, cloud-native data pipelines and integrations. Specialized in building

baseurl: ""
url: "https://lohitinguva.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/

nav:
  - name: Home
    link: /
  - name: Projects
    link: /projects/
  - name: Blog
    link: /blog/
  - name: About
    link: /about/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: pretty
