title: "Lohit Inguva"
description: "Data Engineer | Cloud Architect | Analytics Consultant"
email: "lohitinguva@gmail.com"
baseurl: "" # leave empty for user site
url: "https://lohitinguva.github.io"

author:
  name: "Lohit Inguva"
  avatar: "/assets/images/profile.jpg"
  location: "USA"
  github: "lohitinguva"
  linkedin: "lohitinguva"
  email: "lohitinguva@gmail.com"
  resume: "/assets/files/Lohit_Inguva_Resume.pdf"